"""empty message

Revision ID: 7206e00e44a9
Revises: 68955c107dc8
Create Date: 2017-04-02 16:47:21.027685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7206e00e44a9'
down_revision = '68955c107dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('num_requests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'num_requests')
    # ### end Alembic commands ###
