"""empty message

Revision ID: 24c6c17af4ad
Revises: 7206e00e44a9
Create Date: 2017-04-02 20:32:41.355796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c6c17af4ad'
down_revision = '7206e00e44a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
