"""empty message

Revision ID: e83f5729098f
Revises: 24c6c17af4ad
Create Date: 2017-04-03 09:24:45.498697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83f5729098f'
down_revision = '24c6c17af4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('date', sa.String(), nullable=True))
    op.add_column('request', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'status')
    op.drop_column('request', 'date')
    # ### end Alembic commands ###
